# Generated by Django 4.2 on 2023-08-10 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='service_request_files/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Service Request',
                'db_table': 'tbl_service_request',
            },
        ),
        migrations.CreateModel(
            name='RequestTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Canceled', 'Canceled')], default='Pending', max_length=50)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer_service_app.servicerequest')),
            ],
            options={
                'verbose_name_plural': 'Request Tracking',
                'db_table': 'tbl_request_tracking',
            },
        ),
    ]
